# @package _global_

defaults:
  - override /domain: canaries_t
  - _self_

datamodule:
  input_da:
    _target_: src.utils.load_full_natl_data
    obs_var: five_nadirs
  xrds_kw:
    strides: { time: 1, lat: 200, lon: 200}
  dl_kw: {batch_size: 8}
  aug_factor: 2
  aug_only: False

