# @package _global_

defaults:
  - /params/bigger_model.yaml
  - override /domain: cNATL
  - _self_

trainer:
  accumulate_grad_batches: 6

datamodule:
  input_da:
    _target_: src.utils.load_full_natl_data
    obs_var: five_nadirs
  dl_kw: {batch_size: 8}
  aug_factor: 2
  aug_only: False

start_ckpt: outputs/2023-03-05/12-36-39/base/checkpoints/val_rmse=0.0098-epoch=115.ckpt
