# @package _global_

trainer:
  max_epochs: 600

model:
  _target_: contrib.forecast_ecs.Lit4dVarNetForecast
  persist_rw: false
  opt_fn:
    _target_: contrib.transfert.cosanneal_lr_adamw
    _partial_: true
    lr: 1e-3
    T_max: ${trainer.max_epochs}
    weight_decay: 1e-3
  rec_weight:
    _target_: contrib.forecast_ecs.get_forecast_wei
    patch_dims: ${datamodule.xrds_kw.patch_dims}
    crop: {time: 0, lat: 20, lon: 20}
    offset:  1
  solver:
    _target_: contrib.forecast_ecs.GradSolverZero
    n_step: 10
    lr_grad: 1e3
    prior_cost:
      _target_: src.models.BilinAEPriorCost
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 32
      bilin_quad: false
      downsamp: 2
    obs_cost:
      _target_: src.models.BaseObsCost
    grad_mod:
      _target_: src.models.ConvLstmGradModel
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 48
    weight_obs: 1. 
    weight_prior: 1.
  sampling_rate: 0.01
  norm_type: 'z_score'
  test_metrics: ${metrics.test_metrics}
  pre_metric_fn:
    _target_: xarray.Dataset.sel
    _partial_: True
    #time: {_target_: builtins.slice, _args_: ['2012-10-21', '2013-09-10']}
    time: {_target_: builtins.slice, _args_: ['2013-07-11', '2013-08-20']} #['2013-06-21', '2013-09-10']}
    lat: ${domain.test.lat}
    lon: ${domain.test.lon}
