# @package _global_

## Specific components
sst_da: 
  _target_: contrib.multimodal.load_natl_data_sst
  tgt_path: ${paths.tgt[${entrypoint}]}  # .train or .test
  inp_path: ${paths.inp[${entrypoint}]}  # .train or .test
  sst_path: ${paths.inp_sst[${entrypoint}]}  # .train or .test
  tgt_var: ecs
  inp_var: ecs
  sst_var: sst
  domain: ${domain.train}
  period: ${period[${entrypoint}]}  # .train or .test

obs_cost:
  _target_: contrib.multimodal.MultiModalObsCost
  dim_in: ${datamodule.xrds_kw.patch_dims.time}
  dim_hidden: 5


## Override config
datamodule:
  _target_: contrib.multimodal.MultiModalDataModule
  input_da: ${sst_da}

model:
  solver:
    obs_cost: ${obs_cost}

