# @package xp_overrides
datamodule:
  input_da:
    _target_: contrib.ose2osse.data.load_ose_data
  domains: 
    test: 
      time: {_target_: builtins.slice, _args_: ['2016-12-01', '2018-01-31']}
    train: 
      time: {_target_: builtins.slice, _args_: ['2016-12-01', '2018-01-31']}
  xrds_kw: 
    strides: {lat: 100, lon: 100}
    domain_limits: ${domain.train}
