# @package _global_

patches: {time: 15, lat: 240, lon: 240}

sst_cost: linear

obs_cost_class:
  non_linear: contrib.multimodal.NonLinearMultiModalObsCost
  linear: contrib.multimodal.MultiModalObsCost

obs_cost:
  _target_: ${obs_cost_class.${sst_cost}}
  dim_in: ${patches.time}
  dim_hidden: 5

model:
  rec_weight: {patch_dims: '${patches}'}
  solver:
    prior_cost: {dim_in: '${patches.time}'}
    grad_mod: {dim_in: '${patches.time}'}
    obs_cost: ${obs_cost}
