# @package _global_


patches: {time: 20, lat: 240, lon: 240}

sst: false
datamodule:
  sst: ${sst}
  coarsen: 1
  dl_kws: 
    batch_size: 32
    num_workers: 3
model:
  opt_fn:
    _target_: contrib.uw_convlstm.utils.scotts_lr
    weight_decay: 2e-5
  rec_weight:
    patch_dims: '${patches}'
    crop: {lat: 5, lon: 5}
    offset: 1
  solver: ${convlstm.new_model}

defaults:
  - /params/convlstm@convlstm
