domain:
  train:
    lat:
      _target_: builtins.slice
      _args_:
      - 32
      - 44
    lon:
      _target_: builtins.slice
      _args_:
      - -66
      - -54
  test:
    lat:
      _target_: builtins.slice
      _args_:
      - 33
      - 43
    lon:
      _target_: builtins.slice
      _args_:
      - -65
      - -55
paths:
  natl_gf_5nads: /DATASET/NATL/natl_gf_w_5nadirs.nc
  ose_6_sats: /DATASET/OCB_traces/input_test_6sat_2017.nc
  enatl_gf_5nads: data/enatl_wo_tide.nc
  masks_path: /DATASET/GLORYS12/nadir_obs_masks.pickle
  glorys12_data: /DATASET/GLORYS12/reanalysis/cmems_mod_glo_phy_my_0.083deg_P1D-m_multi-vars_180.00W-179.92E_80.00S-90.00N_0.49m_2020-01-01-2020-12-31.nc
trainer:
  _target_: pytorch_lightning.Trainer
  inference_mode: false
  gradient_clip_val: 0.5
  accelerator: gpu
  devices: 1
  logger:
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: rec_dir
    name: reproduce
    version: ''
  max_epochs: 150
  callbacks:
  - _target_: src.versioning_cb.VersioningCallback
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val_mse
    save_top_k: 3
    filename: '{val_mse:.5f}-{epoch:03d}'
datamodule:
  _target_: src.data.BaseDataModule
  input_da:
    _target_: src.utils.load_ose_data
    path: ${paths.ose_6_sats}
  domains:
    train:
      time:
        _target_: builtins.slice
        _args_:
        - '2023-01-01'
        - '2023-01-02'
    val:
      time:
        _target_: builtins.slice
        _args_:
        - '2023-01-01'
        - '2023-01-02'
    test:
      time:
        _target_: builtins.slice
        _args_:
        - '2023-01-10'
        - '2023-12-20'
  xrds_kw:
    patch_dims:
      time: 29
      lat: 145
      lon: 145
    strides:
      time: 1
      lat: 145
      lon: 145
    domain_limits: ${domain.train}
  dl_kw:
    batch_size: 4
    num_workers: 8
  aug_kw:
    aug_factor: 2
    aug_only: true
model:
  _target_: src.models.Lit4dVarNetForecast
  persist_rw: false
  opt_fn:
    _target_: src.utils.cosanneal_lr_adam
    _partial_: true
    lr: 0.001
    T_max: ${trainer.max_epochs}
  rec_weight:
    _target_: src.utils.get_forecast_wei
    patch_dims: ${datamodule.xrds_kw.patch_dims}
    crop:
      time: 0
      lat: 12
      lon: 12
  solver:
    _target_: src.models.GradSolverZero
    n_step: 10
    lr_grad: 1000.0
    prior_cost:
      _target_: src.models.BilinAEPriorCost
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 64
      bilin_quad: false
    obs_cost:
      _target_: src.models.BaseObsCost
    grad_mod:
      _target_: src.models.ConvLstmGradModel
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 96
  test_metrics: ${metrics.test_metrics}
  pre_metric_fn:
    _target_: xarray.Dataset.sel
    _partial_: true
    time:
      _target_: builtins.slice
      _args_:
      - '2023-01-25'
      - '2023-12-05'
    lat: ${domain.test.lat}
    lon: ${domain.test.lon}
metrics:
  nrmse_scores:
    _target_: src.utils.rmse_based_scores_from_ds
    _partial_: true
  psd_scores:
    _target_: src.utils.psd_based_scores_from_ds
    _partial_: true
  get0:
    _target_: operator.itemgetter
    _args_:
    - 0
  get1:
    _target_: operator.itemgetter
    _args_:
    - 1
  test_metrics:
    mu:
      _target_: src.utils.pipe
      _partial_: true
      fns:
      - ${metrics.nrmse_scores}
      - ${metrics.get0}
    sig:
      _target_: src.utils.pipe
      _partial_: true
      fns:
      - ${metrics.nrmse_scores}
      - ${metrics.get1}
    lx:
      _target_: src.utils.pipe
      _partial_: true
      fns:
      - ${metrics.psd_scores}
      - ${metrics.get0}
    lt:
      _target_: src.utils.pipe
      _partial_: true
      fns:
      - ${metrics.psd_scores}
      - ${metrics.get1}
entrypoints:
- _target_: pytorch_lightning.seed_everything
  seed: 333
- _target_: src.train.base_training
  trainer: ${trainer}
  lit_mod: ${model}
  dm: ${datamodule}
