# @package _global_

paths:
    masks_path: /DATASET/GLORYS12/obs_masks/global_obs_6sats_masks_2022.pickle
    glorys12_data: /DATASET/GLORYS12/reanalysis/glorys12_2010_2019_4th.nc

domain:
  train:
    lat:
      _target_: builtins.slice
      _args_:
      - -80
      - 90
    lon:
      _target_: builtins.slice
      _args_:
      - -180
      - 180
  test:
    lat:
      _target_: builtins.slice
      _args_:
      - -79
      - 89
    lon:
      _target_: builtins.slice
      _args_:
      - -179
      - 179

trainer:
  _target_: pytorch_lightning.Trainer
  inference_mode: False
  gradient_clip_val: 0.5
  accelerator: gpu
  devices: 1
  logger:
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: ${hydra:runtime.output_dir}
    name: ${hydra:runtime.choices.xp}
    version: ''
  max_epochs: 350
  limit_train_batches: 100
  callbacks:
    - _target_: src.versioning_cb.VersioningCallback
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val_mse
      save_top_k: 3
      filename: '{val_mse:.5f}-{epoch:03d}'

datamodule:
  _target_: contrib.moving_patches.movpatch_data_tests.MovingPatchDataModuleFastRecGPU
  input_da: 
    _target_: contrib.data_loading.data.open_glorys12_data
    path: ${paths.glorys12_data}
    masks_path: ${paths.masks_path}
    domain: ${domain.train}
  domains:
    train:
      time: {_target_: builtins.slice, _args_: ['2010-01-01', '2019-05-17']}
    val: 
      time: {_target_: builtins.slice, _args_: ['2019-05-18', '2019-12-31']}
    test: 
      time: {_target_: builtins.slice,  _args_: ['2019-12-31', '2019-12-31']}
  xrds_kw:
    patch_dims: { time: 29, lat: 680, lon: 1440}
    strides: { time: 1, lat: 672, lon: 1432}
    domain_limits: ${domain.train}
  dl_kw: {batch_size: 1, num_workers: 4}
  aug_kw:
    aug_factor: 1
    aug_only: True

model:
  _target_: contrib.forecast_plus.models.Plus4dVarNetForecastPatchGPU
  persist_rw: False
  opt_fn:
    _target_: src.utils.cosanneal_lr_adam
    _partial_: true
    lr: 1e-3
    T_max: ${trainer.max_epochs}
  rec_weight:
    _target_: src.utils.get_forecast_wei
    patch_dims: ${datamodule.xrds_kw.patch_dims}
    crop: {time: 0, lat: 4, lon: 4}
  rec_weight_fn:
    _target_: contrib.forecast_weights.forecast_weights_reconstruction_soft_edges
    _partial_: True
    soft_edge: 0.25
  solver:
    _target_: src.models.GradSolverZero
    n_step: 10
    lr_grad: 1e3
    # lr_grad: 0.2
    prior_cost:
      _target_: src.models.BilinAEPriorCost
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 64
      bilin_quad: False
      # bilin_quad: True
      #downsamp: 2
    obs_cost:
      _target_: src.models.BaseObsCost
    grad_mod:
      _target_: src.models.ConvLstmGradModel
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 96
  pre_metric_fn:
        _target_: xarray.Dataset.sel
        _partial_: True
        time: {_target_: builtins.slice, _args_: ["2019-11-25", "2019-12-31"]}
        lat: ${domain.test.lat}
        lon: ${domain.test.lon}

entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333
  - _target_: src.train.base_training
    trainer: ${trainer}
    lit_mod: ${model}
    dm: ${datamodule}

defaults:
  - _self_

