# @package _global_

paths:
  masks_path: /Odyssey/public/glorys/obs_masks/global_obs_6sats_masks_2022.pickle
  glorys12_data: /Odyssey/public/duacs/2023/duacs_2017_2022_0.25deg.nc
    #duacs_2017_2022_4th.nc
    #duacs_2010_2019_0.25deg.nc
    #2023/duacs_2010_2023.nc
    #Odyssey/public/duacs/2010_2019/duacs_2010_2019_0.25deg.nc
    #023/duacs_2010_2023.nc  #/Odyssey/public/glorys/reanalysis/glorys4_2010_2019_sla.nc for glorys, but for fine tune i am testing : DUACS, to use for masking : 
    #real_traces: /Odyssey/public/altimetry_traces/2010_2023/gridded/sla_l3_all_2010_2023_0.25deg_convl4.nc #ridded_input.n
  real_traces: /Odyssey/public/altimetry_traces/2010_2019/gridded_0.25deg/sla_l3_all_2010_2019_0.25deg_convl4_float32.nc
    # For 6 altimeters : /Odyssey/public/altimetry_traces/2010_2023/gridded/gridded_input.nc
    # For 14 altimetere s: /SCRATCH/d21botvy/all_altimeters.nc
  ref_data_l4: ""
  #ckpt_path: /Odyssey/public/glorys/trainings/forecast_global_1patch_2017_2022_SLA_4dvarnet_real_data_Nadir_Duacs_losses/base_forecast_global_softedge_fastrec_GPU_1patch_10y_SLA_4dvarnet_real_data_from_sratch/checkpoints/val_mse=8.47135-epoch=016.ckpt
    #/Odyssey/public/glorys/trainings/forecast_global_1patch_2017_2022_SLA_4dvarnet_real_data_Nadir_Duacs_losses/base_forecast_global_softedge_fastrec_GPU_1patch_10y_SLA_4dvarnet_real_data_from_sratch/checkpoints/val_mse=7.61364-epoch=006.ckpt
  ose_data_paths: ''
    #/Odyssey/public/glorys/trainings/forecast_global_1patch_10y_SLA_UNet_ResBlock_real_data_Nadir_Duacs_losses/base_forecast_global_softedge_fastrec_GPU_1patch_10y_SLA_UNet_real_data_from_sratch/checkpoints/val_mse=0.01974-epoch=087.ckpt
    #forecast_global_1patch_1y_SLA_UNet_ResBlock_fine_tune/base_forecast_global_softedge_fastrec_GPU_1patch_10y_SLA_UNet_fine_tune/checkpoints/val_mse=9.61748-epoch=024.ckpt
      #UNet best config de base : forecast_global_GPU_1patch_1y_SLA_UNet/base_forecast_global_softedge_fastrec_GPU_1patch_10y_SLA_UNet/checkpoints/val_mse=3.08068-epoch=204.ckpt
      #
      #
      #
var_name: "sla_filtered"


domain:
  train:
    lat:
      _target_: builtins.slice
      _args_:
      - -80
      - 90
    lon:
      _target_: builtins.slice
      _args_:
      - -180
      - 180
  test:
    lat:
      _target_: builtins.slice
      _args_:
      - -79
      - 89
    lon:
      _target_: builtins.slice
      _args_:
      - -179
      - 179

trainer:
  _target_: pytorch_lightning.Trainer
  inference_mode: False
  gradient_clip_val: 0.5
  accelerator: gpu
  devices: 1
  logger:
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: /Odyssey/public/glorys/trainings/forecast_global_1patch_2016_2019_SLA_4dvarnet_OSE_Duacs_loss_latent_dim_21_DoG_v2
    name: ${hydra:runtime.choices.xp}
    version: ''
  max_epochs: 350
  limit_train_batches: 100
  callbacks:
    - _target_: src.versioning_cb.VersioningCallback
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val_mse
      save_top_k: 3
      filename: '{val_mse:.5f}-{epoch:03d}'

datamodule:
  _target_: contrib.moving_patches.movpatch_data_tests.MovingPatchDataModuleFastRecGPUOSE # before DoG loss : without OSE : )
  input_da: 
    _target_: contrib.data_loading.data.open_glorys12_data_sla_OSE #classic for normal loss and OSE for DoG loss
      #open_duacs_data_sla
    path: ${paths.glorys12_data}
    masks_path: ${paths.masks_path}
    real_traces: ${paths.real_traces}
    domain: ${domain.train}
  domains:
    train:
      time: {_target_: builtins.slice, _args_: ['2016-01-01', '2019-04-17']} # previsouly : 2017 to 2022
    val: 
      time: {_target_: builtins.slice, _args_: ['2019-04-18', '2019-11-30']} # previously : '2022-04-18', '2022-11-30'
    test: 
      time: {_target_: builtins.slice,  _args_: ['2019-12-31', '2019-12-31']}
  xrds_kw:
    patch_dims: { time: 21, lat: 680, lon: 1440}
    strides: { time: 1, lat: 672, lon: 1432}
    domain_limits: ${domain.train}
  dl_kw: {batch_size: 1, num_workers: 4}
  aug_kw:
    aug_factor: 1
    aug_only: False # ATTENTION !!!!! CHANGED AUGMENTATION !!!!

model:
  _target_: contrib.forecast_plus.models.Plus4dVarNetForecastPatchGPU_latent_dim        #Plus4dVarNetForecastPatchGPU
  persist_rw: False
  opt_fn:
    _target_: src.utils.cosanneal_lr_adam            #cosanneal_lr_adam
    _partial_: true
    lr: 1e-3
    T_max: ${trainer.max_epochs}
  rec_weight:
    _target_: src.utils.get_forecast_wei
    patch_dims: ${datamodule.xrds_kw.patch_dims}
    crop: {time: 0, lat: 4, lon: 4}
  rec_weight_fn:
    _target_: contrib.forecast_weights.forecast_weights_reconstruction_soft_edges
    _partial_: True
    soft_edge: 0.25
  solver:
    _target_: src.models.GradSolverZero
    n_step: 10
    lr_grad: 1e3
    # lr_grad: 0.2
    prior_cost:
      _target_: src.models.BilinAEPriorCost
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 64
      bilin_quad: False
      # bilin_quad: True
      #downsamp: 2
    obs_cost:
      _target_: src.models.BaseObsCost
    grad_mod:
      _target_: src.models.ConvLstmGradModel
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 96
  pre_metric_fn:
        _target_: xarray.Dataset.sel
        _partial_: True
        time: {_target_: builtins.slice, _args_: ["2019-11-25", "2019-12-31"]}
        lat: ${domain.test.lat}
        lon: ${domain.test.lon}

entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333
  - _target_: src.train.base_training
    trainer: ${trainer}
    lit_mod: ${model}
    dm: ${datamodule}
    #kpt: ${ckpt_path}

defaults:
  - _self_

