# @package _global_

datamodule:
  _target_: contrib.multiprior.MultiPriorDataModule
  input_da:
    _target_: contrib.multiprior.load_data_with_lat_lon
    train_domain: ${domain.train}
  domains:
    train:
      time: {_target_: builtins.slice, _args_: ['2013-02-24', '2013-09-30']}
    val: 
      time: {_target_: builtins.slice, _args_: ['2012-12-15', '2013-02-24']}
    test: 
      time: {_target_: builtins.slice,  _args_: ['2012-10-01', '2012-12-20']}
  xrds_kw:
    patch_dims: { time: 15, lat: 240, lon: 240}
    strides: { time: 1, lat: 200, lon: 200}
    domain_limits: ${domain.train}
  dl_kw: {batch_size: 4, num_workers: 1}
  aug_factor: 5

model:
  _target_: src.models.Lit4dVarNet
  opt_fn:
    _target_: src.utils.cosanneal_lr_adam
    _partial_: true
    lr: 1e-3
    T_max: 300
  rec_weight:
      _target_: src.utils.get_triang_time_wei
      patch_dims: ${datamodule.xrds_kw.patch_dims}
      crop: {time: 0, lat: 20, lon: 20}
      offset: 0
  solver:
    _target_: contrib.multiprior.MultiPriorGradSolver
    n_step: 15
    lr_grad: 0.2
    prior_cost:
      _target_: contrib.multiprior.MultiPriorCost
      prior_costs:
      - _target_: src.models.BilinAEPriorCost
        dim_in: ${datamodule.xrds_kw.patch_dims.time}
        dim_hidden: 64
        downsamp: 2
      # - _target_: src.models.BilinAEPriorCost
      #   dim_in: ${datamodule.xrds_kw.patch_dims.time}
      #   dim_hidden: 32
      #   downsamp: 20
      weight_mod_factory:
        _target_: contrib.multiprior.WeightMod
        _partial_: true
    obs_cost:
      _target_: src.models.BaseObsCost
    grad_mod:
      _target_: src.models.ConvLstmGradModel
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 96

trainer:
  _target_: pytorch_lightning.Trainer
  inference_mode: False
  gradient_clip_val: 0.5
  accelerator: gpu
  devices: 1
  logger: 
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: ${hydra:runtime.output_dir}
    name: ${hydra:runtime.choices.xp}
    version: ''
  max_epochs: 300
  callbacks:
    - _target_: src.versioning_cb.VersioningCallback
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val_rmse
      save_top_k: 10
      filename: '{val_rmse:.4f}-{epoch:03d}'


entrypoints:
  - _target_: lightning_lite.utilities.seed.seed_everything
    _args_:
    - 333
  - _target_: contrib.multiprior.multiprior_train
    trainer: ${trainer}
    model: ${model}
    dm: ${datamodule}
    test_domain:
      time: {_target_: builtins.slice, _args_: ["2012-10-22", "2012-12-02"]}
      lat: ${domain.test.lat}
      lon: ${domain.test.lon}

defaults:
- /domain: gf
- _self_
