# @package _global_

defaults:
  - /xp/base 
  - /params/bigger_model 
  - _self_

trainer:
  max_epochs: 300

start_ckpt: null
test_datamodule: null

osse_datamodule: 
  input_da:
    obs_from_tgt: true
  xrds_kw: ${datamodule.xrds_kw}
  dl_kw: ${datamodule.dl_kw}
  aug_factor: 5
  aug_only: 0

ose_datamodule:
  _target_: src.data.BaseDataModule
  input_da: 
    _target_: contrib.ose2osse.data.load_ose_data
    path: ../sla-data-registry/data_OSE/NATL/training/data_OSE_OSSE_nad.nc
  domains: 
    test: 
      time: {_target_: builtins.slice, _args_: ['2016-12-01', '2018-01-31']}
    train: ${ose_datamodule.domains.test} 
    val: ${ose_datamodule.domains.test} 
  xrds_kw: 
    patch_dims: ${osse_datamodule.xrds_kw.patch_dims}
    strides: ${osse_datamodule.xrds_kw.strides}
    domain_limits: 
      lat: {_target_: builtins.slice, _args_: [32., 44.]}
      lon: {_target_: builtins.slice, _args_: [-66., -54.]}
  dl_kw: {batch_size: 8, num_workers: 1}

diagnostics:
  _target_: contrib.ose2osse.diagnostics.full_ose_osse_test
  _partial_: true
  osse_test_domain:
    time: ${osse_datamodule.domains.test.0.time}
    lat: {_target_: builtins.slice, _args_: [33, 43]}
    lon: {_target_: builtins.slice, _args_: [-65, -55]}
  trainer: ${trainer}
  osse_dm: ${osse_datamodule}
  ose_dm: ${ose_datamodule}
  xp_dir: ${hydra:runtime.output_dir}/${hydra:runtime.choices.xp}
  test_track_path: ../sla-data-registry/data_OSE/along_track/dt_gulfstream_c2_phy_l3_20161201-20180131_285-315_23-53.nc
  oi_path: ../sla-data-registry/data_OSE/NATL/training/ssh_alg_h2g_j2g_j2n_j3_s3a_duacs.nc
  diag_data_dir: ${hydra:runtime.output_dir}/diag_data

entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333
  - _target_: src.train.base_training
    trainer: ${trainer}
    lit_mod: ${model}
    dm: ${osse_datamodule}
    ckpt: ${start_ckpt}
    test_dm: ${test_datamodule}
    test_fn: ${diagnostics}
