# @package _global_

defaults:
  - /xp/ose2osse
  - _self_

entrypoints:
  - _target_: builtins.print
    _args_: ['\n ########## Logging to ${hydra:runtime.output_dir} ######## \n']
  - _target_: pytorch_lightning.seed_everything
    seed: 333
  - _target_: pytorch_lightning.Trainer.test
    self: ${singleton:trainer}
    model: ${singleton:model}
    datamodule: ${singleton:ose_datamodule}
    ckpt_path: ${stages.fit.ckpt_path}
  - _target_: xps.ose2osse.diagnostics.ose_diags
    model: ${singleton:model}
    test_track_path: ../sla-data-registry/data_OSE/along_track/dt_gulfstream_c2_phy_l3_20161201-20180131_285-315_23-53.nc
    oi_path: ../sla-data-registry/data_OSE/NATL/training/ssh_alg_h2g_j2g_j2n_j3_s3a_duacs.nc
    save_rec_path: ${hydra:runtime.output_dir}
      
