# @package _global_

resolution: '1_20'
entrypoint: train  # 'train' or 'test'
checkpoint: null #outputs/2024-03-27/17-21-41/sound_base_comfra/checkpoints/val_mse=2199.81333-epoch=242.ckpt 

#outputs/2024-04-16/14-12-35/sound_base_comfra/checkpoints/val_mse=76.07142-epoch=279.ckpt #0.01 4dvar relative error
#outputs/2024-04-16/14-11-51/sound_base_comfra/checkpoints/val_mse=1407.10178-epoch=300.ckpt  #0.01 4dvar

#outputs/2024-04-04/10-21-05/sound_base_comfra/checkpoints/val_mse=978.39137-epoch=586.ckpt #0.001 4dVar bigger_model z sst acc_grad 2 v2
#outputs/2024-03-27/17-21-41/sound_base_comfra/checkpoints/val_mse=2199.81333-epoch=242.ckpt #0.001 4dVar bigger_model z acc_grad 2
#outputs/2024-03-27/17-20-18/sound_base_comfra/checkpoints/val_mse=2378.24678-epoch=101.ckpt # 0.001 Unet z
#outputs/2024-03-27/16-43-33/sound_base_comfra/checkpoints/val_mse=946.71657-epoch=591.ckpt #0.001 4dVar bigger_model z sst acc_grad 2

#outputs/2024-02-21/18-35-33/sound_base_comfra/checkpoints/val_mse=1454.06590-epoch=213.ckpt # 0.01 Unet z
#outputs/2024-03-27/13-21-21/sound_base_comfra/checkpoints/val_mse=1569.39409-epoch=161.ckpt #0.01 baseline z acc_grad 2
#outputs/2024-03-25/22-15-54/sound_base_comfra/checkpoints/val_mse=1708.48381-epoch=274.ckpt #0.01 baseline z acc_grad 8

#outputs/2024-03-20/17-58-39/sound_base_comfra/checkpoints/val_mse=692.42478-epoch=583.ckpt #0.05 4dVar bigger_model z
#outputs/2024-03-21/09-43-19/sound_base_comfra/checkpoints/val_mse=1285.89242-epoch=592.ckpt #0.01 4dVar bigger_model z acc_grad 8
#outputs/2024-03-22/15-46-58/sound_base_comfra/checkpoints/val_mse=900.49089-epoch=573.ckpt #0.01 4dVar bigger_model z sst acc_grad 8

#outputs/2024-03-01/09-54-36/sound_base_comfra/checkpoints/val_mse=826.14851-epoch=588.ckpt # #0.01 4dVar bigger_model z sst v3

#outputs/2024-03-01/09-54-34/sound_base_comfra/checkpoints/val_mse=1190.60236-epoch=598.ckpt #0.01 4dVar bigger_model z v2
#outputs/2024-03-01/09-54-36/sound_base_comfra/checkpoints/val_mse=826.14851-epoch=588.ckpt # #0.01 4dVar bigger_model z sst v3
# outputs/2024-03-05/10-04-58/sound_base_comfra/checkpoints/val_mse=812.76268-epoch=500.ckpt #0.01 4dVar bigger_model z sst v2

#outputs/2024-02-21/18-29-03/sound_base_comfra/checkpoints/val_mse=822.07630-epoch=296.ckpt #0.01 4dVar bigger_model z sst
#outputs/2024-02-21/18-24-35/sound_base_comfra/checkpoints/val_mse=1294.97376-epoch=268.ckpt #0.01 4dVar bigger_model z
#outputs/2024-02-21/18-23-29/sound_base_comfra/checkpoints/val_mse=1440.81562-epoch=384.ckpt #0.01 4dVar z
#outputs/2024-02-21/18-35-33/sound_base_comfra/checkpoints/val_mse=1454.06590-epoch=213.ckpt # 0.01 Unet z

#checkpoint: 
#outputs/2024-02-19/10-39-31/sound_base_comfra/checkpoints/val_mse=826.88221-epoch=339.ckpt #0.1 z baseline
#outputs/2024-02-13/10-30-53/sound_base_comfra/checkpoints/val_mse=595.82034-epoch=382.ckpt #0.1 z
#outputs/2024-02-13/18-11-53/sound_base_comfra/checkpoints/val_mse=776.64259-epoch=382.ckpt #0.05 z
#outputs/2024-02-20/10-23-18/sound_base_comfra/checkpoints/val_mse=547.78453-epoch=390.ckpt  #0.1 z sst
#outputs/2024-02-20/10-35-02/sound_base_comfra/checkpoints/val_mse=546.50232-epoch=390.ckpt #0.1 z ssh

val_period:
  time:
    _target_: builtins.slice
    _args_:
      - 2010-04-10-12
      - 2010-06-30-12

paths:
    inp:
      train: '/DATASET/eNATL/eNATL60_BLB002_cutoff_freq_regrid_0_1000m.nc'
      test: '/DATASET/NATL/NATL60GULF-CJM165_cutoff_freq_regrid_0_1000m.nc'

    inp_sst: 
      train: '/DATASET/eNATL/eNATL60-BLB002-SST-GF-2009-2010-1_20.nc'
      test: '/DATASET/NATL/NATL60-CJM165_NATL_sst_y2013.1y.nc'
    
    inp_ssh: 
      train: /DATASET/eNATL/eNATL60_BLB002_SSH_nadirs/eNATL60-BLB002-ssh-2009-2010-${resolution}.nc
      #train: /DATASET/eNATL/eNATL60_BLB002_SSH_nadirs/eNATL60-BLB002-7nadirs-2009-2010-${resolution}.nc
      test: /DATASET/NATL/NATL60-CJM165-ssh-2012-2013-${resolution}.nc
    
    tgt:
      train: '/DATASET/eNATL/eNATL60_BLB002_cutoff_freq_regrid_0_1000m.nc'
      test: '/DATASET/NATL/NATL60GULF-CJM165_cutoff_freq_regrid_0_1000m.nc'
    
    tgt_sst:
      train: '/DATASET/eNATL/eNATL60-BLB002-SST-GF-2009-2010-1_20.nc'
      test: '/DATASET/NATL/NATL60-CJM165_NATL_GF_sst_y2013.1y.nc'

    tgt_ssh:  
      train: /DATASET/eNATL/eNATL60_BLB002_SSH_nadirs/eNATL60-BLB002-ssh-2009-2010-${resolution}.nc
      test: /DATASET/NATL/NATL60-CJM165-ssh-2012-2013-${resolution}.nc

trainer:
  _target_: pytorch_lightning.Trainer
  inference_mode: false
  gradient_clip_val: 0.5
  accelerator: gpu
  devices: 1
  logger:
    _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    save_dir: ${hydra:runtime.output_dir}
    name: ${hydra:runtime.choices.xp}
    version: ''
  max_epochs: 400
  accumulate_grad_batches: 2
  callbacks:
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val_mse
      save_top_k: 3
      filename: '{val_mse:.5f}-{epoch:03d}'

datamodule:
  _target_: src.data.BaseDataModule_comfra
  input_da:
    _target_: src.utils.load_natl_data
    tgt_path: ${paths.tgt[${entrypoint}]}  # .train or .test
    inp_path: ${paths.inp[${entrypoint}]}  # .train or .test
    tgt_var: ecs
    inp_var: ecs
    domain: ${domain.train}
    period: ${period[${entrypoint}]}
  domains:
    train: ${period.train}
    val: ${val_period}
    test:
      time: {_target_: builtins.slice, _args_: ['2013-06-01', '2013-08-30']}
  xrds_kw:
    patch_dims: { time: 15, lat: 240, lon: 240}
    strides: { time: 1, lat: 200, lon: 200}
    domain_limits: ${domain.train}
  dl_kw: {batch_size: 4, num_workers: 1}
  aug_kw:
    aug_factor: 2
    aug_only: true
  norm_type: 'z_score'

model:
  _target_: src.models.Lit4dVarNet
  persist_rw: false
  opt_fn:
    _target_: src.utils.cosanneal_lr_adamw
    _partial_: true
    lr: 1e-3
    T_max: ${trainer.max_epochs}
    weight_decay: 1e-2
  rec_weight:
      _target_: src.utils.get_triang_time_wei
      patch_dims: ${datamodule.xrds_kw.patch_dims}
      crop: {time: 0, lat: 20, lon: 20}
      offset: 1
  solver:
    _target_: src.models.GradSolver
    n_step: 10
    lr_grad: 1e3
    prior_cost:
      _target_: src.models.BilinAEPriorCost
      #weight3: 1. 
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 32
      bilin_quad: false
      downsamp: 2
    obs_cost:
      _target_: src.models.BaseObsCost
      #weight1: 1. 
      #weight2: 1.
    grad_mod:
      _target_: src.models.ConvLstmGradModel
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 48
  sampling_rate: 0.01
  norm_type: 'z_score'
  test_metrics: ${metrics.test_metrics}
  pre_metric_fn:
    _target_: xarray.Dataset.sel
    _partial_: true
    time: ${period.test.time}
    #time: {_target_: builtins.slice, _args_: ['2012-10-01', '2012-12-20']}
    lat: ${domain.test.lat}
    lon: ${domain.test.lon}

metrics:
  nrmse_scores: {_target_: src.utils.rmse_based_scores_from_ds, _partial_: true}
  psd_scores: {_target_: src.utils.psd_based_scores_from_ds, _partial_: true}
  get0: {_target_: operator.itemgetter, _args_: [0]}
  get1: {_target_: operator.itemgetter, _args_: [1]}
  test_metrics:
    'μ': {_target_: src.utils.pipe, _partial_: true, fns: ['${metrics.nrmse_scores}', '${metrics.get0}']}
    'σ': {_target_: src.utils.pipe, _partial_: true, fns: ['${metrics.nrmse_scores}', '${metrics.get1}']}
    'λx': {_target_: src.utils.pipe, _partial_: true, fns: ['${metrics.psd_scores}', '${metrics.get0}']}
    'λt': {_target_: src.utils.pipe, _partial_: true, fns: ['${metrics.psd_scores}', '${metrics.get1}']}

entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333
  - _target_: src.train.base_training
    trainer: ${trainer}
    lit_mod: ${model}
    dm: ${datamodule}
    ckpt: ${checkpoint}

defaults:
  - /domain: gf
  - /period: midsummer
  # - /period@val_period: midsummer
  - _self_