# @package _global_

paths:
    masks_path: /Odyssey/public/glorys/obs_masks/global_obs_6sats_masks_2022.pickle 
    glorys12_data: /Odyssey/public/REMSS_SST/data/sst_l3_0.25deg_2010_2021_REMSS_AMSR2.nc
      #/Odyssey/public/ODYSSEA_IFREMER_SST/L3_NRT/CLIMATO/SST-L3-NRT-2024_2026_NRT_ANOMALY_CLIMATO_f32_0.25deg_pyresample_adjusted_sst_flagged_5.nc #SST-L3-2010_2023_ANOMALY_CLIMATO_f32_0.5deg_pyresample.nc
      #L3_NRT/sst_l3_nrt_2024_2026_climato_anomaly_f32.nc
      #CLIMATO/IFREMER-GLOB-SST-L3-NRT-2021_2022_ANOMALY_CLIMATO_f32_0.5deg.nc #/Odyssey/public/ODYSSEA_IFREMER_SST/CLIMATO/sst_anomaly_L3_f32_compressed.nc
    full_l4_path: /Odyssey/public/ODYSSEA_IFREMER_SST/CLIMATO/SST-L3-NRT-2010_2019_ANOMALY_CLIMATO_f32_0.25deg_pyresample_adjusted_sst.nc
      #SST-L4-NRT-2024_2026_NRT_ANOMALY_CLIMATO_f32_0.25deg_remapbil.nc #SST-L4-2010_2020_ANOMALY_CLIMATO_f32_0.5deg_pyresample.nc
      #L4_NRT/sst_l4_nrt_2024_2026_climato_anomaly_f32.nc
      #L4/sst_l4_nrt_2021_2022_climato.nc #CLIMATO/sst_anomaly_f32_compressed.nc
    ref_data_l4: #/Odyssey/public/ODYSSEA_IFREMER_SST/L4/sst_l4_nrt_2023_remapbil_0.25deg.nc #/Odyssey/public/ODYSSEA_IFREMER_SST/L3_NRT/sst_l3_nrt_2023_climato_anomaly_f32_original_resolution.nc
      #CLIMATO/sst_anomaly_f32_compressed.nc #/Odyssey/public/ODYSSEA_IFREMER_SST/L4_NRT/sst_l4_nrt_2024_2026_climato_anomaly_f32.nc
      #CLIMATO/sst_anomaly_f32_compressed.nc #CLIMATO/sst_anomaly_f32_compressed.nc #mems_obs-sst_glo_phy_nrt_l4_P1D-m_multi-vars_179.95W-179.95E_79.95S-79.95N_2021-01-01-2022-12-31.nc
    ose_data_paths: #/Odyssey/public/ODYSSEA_IFREMER_SST/CLIMATO/SST-L3-NRT-2023_NRT_ANOMALY_CLIMATO_f32_0.25deg_FLAG_5_REAL.nc
      #Odyssey/public/ODYSSEA_IFREMER_SST/CLIMATO/SST-L3-NRT-2023_NRT_ANOMALY_CLIMATO_f32_0.25deg_pyresample_adjusted_sst_flagged_5.nc
      #/Odyssey/public/REMSS_SST/data/daily_2023/SST-L3-2023_AMSR2_ANOMALY_CLIMATO_daily_f32_flagged_5.nc
      #Odyssey/public/ODYSSEA_IFREMER_SST/CLIMATO/SST-L3-NRT-2023_NRT_ANOMALY_CLIMATO_f32_0.25deg_pyresample_adjusted_sst.nc #/Odyssey/public/ODYSSEA_IFREMER_SST/CLIMATO/SST-L3-NRT-2023_ANOMALY_CLIMATO_f32_0.5deg_pyresample_v2.nc  #/Odyssey/public/ODYSSEA_IFREMER_SST/L3_NRT/sst_l3_nrt_2023_climato_anomaly_f32_original_resolution.nc
      #CLIMATO/IFREMER-GLOB-SST-L3-NRT-2021_2025_ANOMALY_CLIMATO_f32.nc #/Odyssey/public/ODYSSEA_IFREMER_SST/IFREMER-GLOB-SST-L3-NRT-OBS_FULL_TIME_SERIE_multi-vars_179.95W-179.95E_79.95S-79.95N_2021-01-01-2025-07-10.nc

var_name: "sst_anomaly" #"sea_surface_temperature"
year_ose: 2023



domain:
  train:
    lat:
      _target_: builtins.slice
      _args_:
      - -90
      - 90
    lon:
      _target_: builtins.slice
      _args_:
      - -180
      - 180
  test:
    lat:
      _target_: builtins.slice
      _args_:
      - -90
      - 90
    lon:
      _target_: builtins.slice
      _args_:
      - -180
      - 180

trainer:
  _target_: pytorch_lightning.Trainer
  inference_mode: False
  gradient_clip_val: 0.5
  accelerator: gpu
  devices: 1
  logger:
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: /Odyssey/public/glorys/trainings/forecast_global_GPU_1patch_SST_ODYSSEA_UNet_ResBlock_17M_2012_2019_microwave_amsr2_pyresample_0.25deg_lossMSE+Grad_AugFalse
    name: ${hydra:runtime.choices.xp}
    version: ''
  max_epochs: 895 #700 + 195 # 350 before
  limit_train_batches: 100
  callbacks:
    - _target_: src.versioning_cb.VersioningCallback
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val_mse
      save_top_k: 10
      filename: '{val_mse:.5f}-{epoch:03d}'

datamodule:
  _target_: contrib.moving_patches.movpatch_data_tests.MovingPatchDataModuleFastRecGPU # _SST before 
  input_da: 
    _target_: contrib.data_loading.data.open_glorys12_data_sst_normalized_climato
    path: ${paths.glorys12_data}
    masks_path: ${paths.masks_path}
    full_l4_path: ${paths.full_l4_path}
    domain: ${domain.train}
    masking: False
    time_domains: {_target_: builtins.slice, _args_: ['2012-07-10', '2019-12-31']}
  domains:
    train:
      time: {_target_: builtins.slice, _args_: ['2012-07-10', '2018-12-31']}
    val: 
      time: {_target_: builtins.slice, _args_: ['2019-01-01', '2019-12-31']}
    test: 
      time: {_target_: builtins.slice,  _args_: ['2019-01-01', '2019-03-01']}
  xrds_kw:
    patch_dims: { time: 29, lat: 720, lon: 1440} #{ time: 29, lat: 1600, lon: 3600} #{ time: 29, lat: 360, lon: 720}
    strides: { time: 1, lat: 716, lon: 1436} #{time: 1, lat: 1580, lon: 3580} # { time: 1, lat: 356, lon: 716}
    domain_limits: ${domain.train}
  dl_kw: {batch_size: 1, num_workers: 4}
  aug_kw:
    aug_factor: 1
    aug_only: False # no augmentation for real data !!!
  #norm_stats: [0.12338143086501935, 0.7525210465610936] # [0.12782835761816647, 0.7870184277193579]

model:
  _target_: contrib.forecast_plus.models.Plus4dVarNetForecastPatchGPU_UNet_SST
  persist_rw: False
  opt_fn:
    _target_: src.utils.cosanneal_lr_adam_UNet            #cosanneal_lr_adam
    _partial_: true
    lr: 1e-3
    T_max: ${trainer.max_epochs}
  rec_weight:
    _target_: src.utils.get_forecast_wei
    patch_dims: ${datamodule.xrds_kw.patch_dims}  #crop: {time: 0, lat: 4, lon: 4}
    crop: {time: 0, lat: 4, lon: 4} #{time: 0, lat: 40, lon: 40}  #{time: 0, lat: 2, lon: 2}
  rec_weight_fn:
    _target_: contrib.forecast_weights.forecast_weights_reconstruction_soft_edges
    _partial_: True
    soft_edge: 0.25
  solver:
    _target_: src.models_UNet.UNet    #GradSolverZero
    n_channels: 29
    n_classes: 29
    bilinear: True
    block: 
      _target_: src.parts.ResBlock
      _partial_: True
    add_input: False
      #n_step: 10
      #lr_grad: 1e3
    # lr_grad: 0.2
    #prior_cost:
    # _target_: src.models.BilinAEPriorCost
    # dim_in: ${datamodule.xrds_kw.patch_dims.time}
    # dim_hidden: 64
    # bilin_quad: False
      # bilin_quad: True
      #downsamp: 2
    # obs_cost:
    #_target_: src.models.BaseObsCost
    #grad_mod:
    # _target_: src.models.ConvLstmGradModel
    # dim_in: ${datamodule.xrds_kw.patch_dims.time}
    # dim_hidden: 96
  pre_metric_fn:
        _target_: xarray.Dataset.sel
        _partial_: True
        time: {_target_: builtins.slice, _args_: ["2022-11-25", "2022-12-31"]}
        lat: ${domain.test.lat}
        lon: ${domain.test.lon}

entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333
  - _target_: src.train.base_training
    trainer: ${trainer}
    lit_mod: ${model}
    dm: ${datamodule}
      #ckpt: /Odyssey/public/glorys/trainings/forecast_global_GPU_1patch_SST_ODYSSEA_UNet_ResBlock_17M_2010_2019_AugTrue_MSE+GradLoss_LatLon/sst_training_anomalyClimato_MSE_2016_2019/checkpoints/val_mse=0.09358-epoch=034.ckpt
    #/Odyssey/public/glorys/trainings/forecast_global_GPU_1patch_SST_ODYSSEA_UNet_ResBlock_17M_2010_2019_AugTrue_MSE/sst_training_anomalyClimato_MSE_2016_2019/checkpoints/val_mse=0.09618-epoch=056.ckpt

defaults:
  - _self_

