# @package _global_
xpd: ???


domain: ???
xp_overrides: 
  datamodule:
    input_da:
      _target_: src.utils.load_enatl
    domains:
      val: {time: {_args_: ["2009-08-01", "2010-09-30"]}}
      test: {time: {_args_: ["2009-08-01", "2010-12-30"]}}
      train: {time: {_args_: ["2010-01-01", "2010-06-30"]}}
    xrds_kw: 
      strides: {lat: 100, lon: 100}
      domain_limits: ${domain.train}
  
trainer: 
  _target_: pytorch_lightning.Trainer
  inference_mode: False
  accelerator: gpu
  devices: 1
  logger: False

lit_mod: 
  _target_: contrib.multi_domain_diag.load_cfg_from_xp
  key: model
  xpd : ${xpd}
  overrides: ${xp_overrides}

dm: 
  _target_: contrib.multi_domain_diag.load_cfg_from_xp
  key: datamodule
  xpd : ${xpd}
  overrides: ${xp_overrides}

ckpt: 
  _target_: src.utils.best_ckpt
  xp_dir: ${xpd}/base

test_domains: 
  train: ${domain}

test_periods: [["2009-10-22", "2009-12-02"]]

rec_weight:
  _target_: contrib.multi_domain_diag.get_smooth_spat_rec_weight
  orig_rec_weight: 
    _target_: contrib.multi_domain_diag.load_cfg_from_xp
    key: model.rec_weight
    xpd : ${xpd}

entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333
  - _target_: contrib.multi_domain_diag.multi_domain_osse_diag
    trainer: ${trainer}
    lit_mod: ${lit_mod}
    dm: ${dm}
    ckpt_path: ${ckpt}
    rec_weight: ${rec_weight}
    test_domains: ${test_domains}
    test_periods: ${test_periods}
    save_dir: ${hydra:runtime.output_dir}
defaults:
  - /domain: ???
  - _self_

