# @package _global_
xpd: outputs/2024-06-20/15-16-55/

xp_overrides:

trainer:
  _target_: pytorch_lightning.Trainer
  inference_mode: False
  accelerator: gpu
  devices: 1
  logger: 
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: ${hydra:runtime.output_dir}
    name: ${hydra:runtime.choices.xp}
    version: ''

lit_mod:
  _target_: contrib.multi_domain_diag.load_cfg_from_xp
  key: model
  xpd : ${xpd}
  overrides: ${xp_overrides}

dm:
  _target_: contrib.multi_domain_diag.load_cfg_from_xp
  key: datamodule
  xpd : ${xpd}
  overrides: ${xp_overrides}

ckpt:
  _target_: src.utils.best_ckpt
  xp_dir: ${xpd}

entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333
  - _target_: pytorch_lightning.Trainer.test
    self: ${trainer}
    model: ${lit_mod}
    datamodule: ${dm}
    ckpt_path: ${ckpt}

defaults:
  - _self_

